[colors]

# Normal colors
foreground       = '#4C4F69'
background       = '#EFF1F5'
black            = '#5C5F77'
blue             = '#1E66F5'
cursor           = '#DC8A78'
cyan             = '#179299'
green            = '#40A02B'
magenta          = '#EA76CB'
red              = '#D20F39'
white            = '#ACB0BE'
yellow           = '#DF8E1D'

# UI colors
tabs             = '#1E1E2E'
tabs-active      = '#B4BEFE'
selection-foreground = '#EFF1F5'
selection-background = '#DC8A78'

# Dim colors
dim-black        = '#5C5F77'
dim-blue         = '#1E66F5'
dim-cyan         = '#179299'
dim-foreground   = '#4C4F69'
dim-green        = '#40A02B'
dim-magenta      = '#EA76CB'
dim-red          = '#D20F39'
dim-white        = '#ACB0BE'
dim-yellow       = '#DF8E1D'

# Light colors
light-black      = '#6C6F85'
light-blue       = '#1E66F5'
light-cyan       = '#179299'
light-foreground = '#4C4F69'
light-green      = '#40A02B'
light-magenta    = '#EA76CB'
light-red        = '#D20F39'
light-white      = '#BCC0CC'
light-yellow     = '#DF8E1D'
